/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Maze;
import java.awt.Graphics;

/**
 *
 * @author Eduardo
 */
public class MazePanel extends javax.swing.JPanel {

    /**
     * Creates new form Laberinto
     */
    
    
    Maze myMaze;
    
    public MazePanel() {
        initComponents();
        myMaze = Maze.getInstance();
        setLocation(200, 200);
    }
    
  
    //Método que dibuja los cuadros segun la matriz del laberinto
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int ancho = getWidth()/myMaze.getMaze()[0].length;
        int large = getHeight()/myMaze.getMaze().length;
        for (int i = 0; i < myMaze.getMaze().length; i++) {
            for (int j = 0; j <myMaze.getMaze()[0].length; j++) {
                if(myMaze.getMaze()[i][j] == 1){
                    g.fillRect(ancho*j, large*i, ancho, large);
                }
            }
        }
    } //fin metodo paintComponent

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
