/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paula
 */
public class WelcomeFrame extends javax.swing.JFrame {

    ChoosePanel choosepanel;
            
    public WelcomeFrame() {
        initComponents();
        setLocation(350,50);
        btnstart.setOpaque(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblwelcome = new javax.swing.JLabel();
        lblwelcome2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnstart = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        lblwelcome.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblwelcome.setText("Welcome to");
        getContentPane().add(lblwelcome);
        lblwelcome.setBounds(90, 50, 350, 80);

        lblwelcome2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblwelcome2.setForeground(new java.awt.Color(255, 102, 0));
        lblwelcome2.setText("MazeDragon");
        getContentPane().add(lblwelcome2);
        lblwelcome2.setBounds(330, 90, 200, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/charizard.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 140, 510, 220);

        btnstart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/go.png"))); // NOI18N
        btnstart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });
        getContentPane().add(btnstart);
        btnstart.setBounds(580, 450, 90, 80);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/maze-wallpapers.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 970, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
       this.setVisible(false);
        try {
            choosepanel = new ChoosePanel();
            choosepanel.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WelcomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       
    }//GEN-LAST:event_btnstartActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JLabel lblwelcome2;
    // End of variables declaration//GEN-END:variables
}
